### ISSUE TITLE
Can't get boilerplate of Node Basic

### ISSUE THREAD

**Issue by noderme** [graphql-boilerplates/node-graphql-server#194]
graphql create hackernews-node --boilerplate node-basic

[graphql create] Downloading boilerplate from https://github.com/graphql-boilerplates/node-graphql-server/archive/master.zip...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 192.168.1.1:8080
    at ClientRequest.onError (C:\Users\MADMAN\AppData\Roaming\npm\node_modules\graphql-cli\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by kbrandwijk** [comment]
@bennykelly That has to do with your Node version, you need at least 8.x or 9.

**Comment by kbrandwijk** [comment]
@noderme Have you set a proxy by any chance as an env var (`HTTPS_PROXY`)?

**Comment by noderme** [comment]
@kbrandwijk Hi, Yeah ,I set proxy.

**Comment by kbrandwijk** [comment]
@noderme Can you try it without, so we can rule that out?

**Comment by noderme** [comment]
Hi @kbrandwijk  I successfully made it by removing proxy from both environment variables and NPM. not using proxy internet,
